# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_mce.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import os
path = os.path.dirname(os.path.abspath(__file__))


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(748, 860)
        MainWindow.setStatusTip("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_Name = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_Name.setFont(font)
        self.label_Name.setObjectName("label_Name")
        self.horizontalLayout.addWidget(self.label_Name)
        self.lineEdit_Name = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Name.setMinimumSize(QtCore.QSize(191, 20))
        self.lineEdit_Name.setMaximumSize(QtCore.QSize(191, 20))
        self.lineEdit_Name.setObjectName("lineEdit_Name")
        self.horizontalLayout.addWidget(self.lineEdit_Name)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label_Database = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_Database.setFont(font)
        self.label_Database.setObjectName("label_Database")
        self.horizontalLayout.addWidget(self.label_Database)
        self.comboBox_Database = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_Database.setMinimumSize(QtCore.QSize(181, 22))
        self.comboBox_Database.setMaximumSize(QtCore.QSize(181, 22))
        self.comboBox_Database.setObjectName("comboBox_Database")
        self.horizontalLayout.addWidget(self.comboBox_Database)
        self.pushButton_Save = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Save.setMinimumSize(QtCore.QSize(75, 23))
        self.pushButton_Save.setMaximumSize(QtCore.QSize(75, 23))
        self.pushButton_Save.setObjectName("pushButton_Save")
        self.horizontalLayout.addWidget(self.pushButton_Save)
        self.pushButton_Delete = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Delete.setMinimumSize(QtCore.QSize(75, 23))
        self.pushButton_Delete.setMaximumSize(QtCore.QSize(75, 23))
        self.pushButton_Delete.setObjectName("pushButton_Delete")
        self.horizontalLayout.addWidget(self.pushButton_Delete)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.group_Parameters = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.group_Parameters.setFont(font)
        self.group_Parameters.setObjectName("group_Parameters")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.group_Parameters)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_J = QtWidgets.QLabel(self.group_Parameters)
        self.label_J.setMinimumSize(QtCore.QSize(16, 16))
        self.label_J.setMaximumSize(QtCore.QSize(16, 16))
        self.label_J.setText("")
#        self.label_J.setPixmap(QtGui.QPixmap("fig_J.png"))
        self.label_J.setScaledContents(True)
        self.label_J.setObjectName("label_J")
        self.horizontalLayout_2.addWidget(self.label_J)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.lineEdit_J = QtWidgets.QLineEdit(self.group_Parameters)
        self.lineEdit_J.setMinimumSize(QtCore.QSize(113, 20))
        self.lineEdit_J.setMaximumSize(QtCore.QSize(113, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_J.setFont(font)
        self.lineEdit_J.setObjectName("lineEdit_J")
        self.horizontalLayout_2.addWidget(self.lineEdit_J)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_gJ = QtWidgets.QLabel(self.group_Parameters)
        self.label_gJ.setMinimumSize(QtCore.QSize(21, 16))
        self.label_gJ.setMaximumSize(QtCore.QSize(21, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_gJ.setFont(font)
        self.label_gJ.setText("")
#        self.label_gJ.setPixmap(QtGui.QPixmap("fig_gJ.png"))
        self.label_gJ.setScaledContents(True)
        self.label_gJ.setObjectName("label_gJ")
        self.horizontalLayout_3.addWidget(self.label_gJ)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.lineEdit_gJ = QtWidgets.QLineEdit(self.group_Parameters)
        self.lineEdit_gJ.setMinimumSize(QtCore.QSize(113, 20))
        self.lineEdit_gJ.setMaximumSize(QtCore.QSize(113, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_gJ.setFont(font)
        self.lineEdit_gJ.setObjectName("lineEdit_gJ")
        self.horizontalLayout_3.addWidget(self.lineEdit_gJ)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_TC1 = QtWidgets.QLabel(self.group_Parameters)
        self.label_TC1.setMinimumSize(QtCore.QSize(51, 21))
        self.label_TC1.setMaximumSize(QtCore.QSize(51, 21))
        self.label_TC1.setText("")
#        self.label_TC1.setPixmap(QtGui.QPixmap("fig_TC1.png"))
        self.label_TC1.setScaledContents(True)
        self.label_TC1.setObjectName("label_TC1")
        self.horizontalLayout_4.addWidget(self.label_TC1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.lineEdit_TC1 = QtWidgets.QLineEdit(self.group_Parameters)
        self.lineEdit_TC1.setMinimumSize(QtCore.QSize(113, 20))
        self.lineEdit_TC1.setMaximumSize(QtCore.QSize(113, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_TC1.setFont(font)
        self.lineEdit_TC1.setObjectName("lineEdit_TC1")
        self.horizontalLayout_4.addWidget(self.lineEdit_TC1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_TC2 = QtWidgets.QLabel(self.group_Parameters)
        self.label_TC2.setMinimumSize(QtCore.QSize(51, 21))
        self.label_TC2.setMaximumSize(QtCore.QSize(51, 21))
        self.label_TC2.setText("")
#        self.label_TC2.setPixmap(QtGui.QPixmap("fig_TC2.png"))
        self.label_TC2.setScaledContents(True)
        self.label_TC2.setObjectName("label_TC2")
        self.horizontalLayout_5.addWidget(self.label_TC2)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.lineEdit_TC2 = QtWidgets.QLineEdit(self.group_Parameters)
        self.lineEdit_TC2.setMinimumSize(QtCore.QSize(113, 20))
        self.lineEdit_TC2.setMaximumSize(QtCore.QSize(113, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_TC2.setFont(font)
        self.lineEdit_TC2.setObjectName("lineEdit_TC2")
        self.horizontalLayout_5.addWidget(self.lineEdit_TC2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_ThetaD1 = QtWidgets.QLabel(self.group_Parameters)
        self.label_ThetaD1.setMinimumSize(QtCore.QSize(61, 21))
        self.label_ThetaD1.setMaximumSize(QtCore.QSize(61, 21))
        self.label_ThetaD1.setText("")
#        self.label_ThetaD1.setPixmap(QtGui.QPixmap("fig_ThetaD1.png"))
        self.label_ThetaD1.setScaledContents(True)
        self.label_ThetaD1.setObjectName("label_ThetaD1")
        self.horizontalLayout_6.addWidget(self.label_ThetaD1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.lineEdit_ThetaD1 = QtWidgets.QLineEdit(self.group_Parameters)
        self.lineEdit_ThetaD1.setMinimumSize(QtCore.QSize(113, 20))
        self.lineEdit_ThetaD1.setMaximumSize(QtCore.QSize(113, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_ThetaD1.setFont(font)
        self.lineEdit_ThetaD1.setObjectName("lineEdit_ThetaD1")
        self.horizontalLayout_6.addWidget(self.lineEdit_ThetaD1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_ThetaD2 = QtWidgets.QLabel(self.group_Parameters)
        self.label_ThetaD2.setMinimumSize(QtCore.QSize(61, 21))
        self.label_ThetaD2.setMaximumSize(QtCore.QSize(61, 21))
        self.label_ThetaD2.setText("")
#        self.label_ThetaD2.setPixmap(QtGui.QPixmap("fig_ThetaD2.png"))
        self.label_ThetaD2.setScaledContents(True)
        self.label_ThetaD2.setObjectName("label_ThetaD2")
        self.horizontalLayout_7.addWidget(self.label_ThetaD2)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self.lineEdit_ThetaD2 = QtWidgets.QLineEdit(self.group_Parameters)
        self.lineEdit_ThetaD2.setMinimumSize(QtCore.QSize(113, 20))
        self.lineEdit_ThetaD2.setMaximumSize(QtCore.QSize(113, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_ThetaD2.setFont(font)
        self.lineEdit_ThetaD2.setObjectName("lineEdit_ThetaD2")
        self.horizontalLayout_7.addWidget(self.lineEdit_ThetaD2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_DeltaF = QtWidgets.QLabel(self.group_Parameters)
        self.label_DeltaF.setMinimumSize(QtCore.QSize(71, 21))
        self.label_DeltaF.setMaximumSize(QtCore.QSize(71, 21))
        self.label_DeltaF.setText("")
#        self.label_DeltaF.setPixmap(QtGui.QPixmap("fig_DeltaF.png"))
        self.label_DeltaF.setScaledContents(True)
        self.label_DeltaF.setObjectName("label_DeltaF")
        self.horizontalLayout_8.addWidget(self.label_DeltaF)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem9)
        self.lineEdit_DeltaF = QtWidgets.QLineEdit(self.group_Parameters)
        self.lineEdit_DeltaF.setMinimumSize(QtCore.QSize(113, 20))
        self.lineEdit_DeltaF.setMaximumSize(QtCore.QSize(113, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_DeltaF.setFont(font)
        self.lineEdit_DeltaF.setObjectName("lineEdit_DeltaF")
        self.horizontalLayout_8.addWidget(self.lineEdit_DeltaF)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_N = QtWidgets.QLabel(self.group_Parameters)
        self.label_N.setMinimumSize(QtCore.QSize(21, 16))
        self.label_N.setMaximumSize(QtCore.QSize(21, 16))
        self.label_N.setText("")
#        self.label_N.setPixmap(QtGui.QPixmap("fig_N.png"))
        self.label_N.setScaledContents(True)
        self.label_N.setObjectName("label_N")
        self.horizontalLayout_9.addWidget(self.label_N)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem10)
        self.lineEdit_N = QtWidgets.QLineEdit(self.group_Parameters)
        self.lineEdit_N.setMinimumSize(QtCore.QSize(113, 20))
        self.lineEdit_N.setMaximumSize(QtCore.QSize(113, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_N.setFont(font)
        self.lineEdit_N.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_N.setObjectName("lineEdit_N")
        self.horizontalLayout_9.addWidget(self.lineEdit_N)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_Nm = QtWidgets.QLabel(self.group_Parameters)
        self.label_Nm.setMinimumSize(QtCore.QSize(31, 16))
        self.label_Nm.setMaximumSize(QtCore.QSize(31, 16))
        self.label_Nm.setText("")
#        self.label_Nm.setPixmap(QtGui.QPixmap("fig_Nm.png"))
        self.label_Nm.setScaledContents(True)
        self.label_Nm.setObjectName("label_Nm")
        self.horizontalLayout_10.addWidget(self.label_Nm)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem11)
        self.lineEdit_Nm = QtWidgets.QLineEdit(self.group_Parameters)
        self.lineEdit_Nm.setMinimumSize(QtCore.QSize(113, 20))
        self.lineEdit_Nm.setMaximumSize(QtCore.QSize(113, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_Nm.setFont(font)
        self.lineEdit_Nm.setObjectName("lineEdit_Nm")
        self.horizontalLayout_10.addWidget(self.lineEdit_Nm)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.line = QtWidgets.QFrame(self.group_Parameters)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_Ti = QtWidgets.QLabel(self.group_Parameters)
        self.label_Ti.setMinimumSize(QtCore.QSize(51, 21))
        self.label_Ti.setMaximumSize(QtCore.QSize(51, 21))
        self.label_Ti.setText("")
#        self.label_Ti.setPixmap(QtGui.QPixmap("fig_Ti.png"))
        self.label_Ti.setScaledContents(True)
        self.label_Ti.setObjectName("label_Ti")
        self.horizontalLayout_11.addWidget(self.label_Ti)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem12)
        self.lineEdit_Ti = QtWidgets.QLineEdit(self.group_Parameters)
        self.lineEdit_Ti.setMinimumSize(QtCore.QSize(113, 20))
        self.lineEdit_Ti.setMaximumSize(QtCore.QSize(113, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_Ti.setFont(font)
        self.lineEdit_Ti.setObjectName("lineEdit_Ti")
        self.horizontalLayout_11.addWidget(self.lineEdit_Ti)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_Tf = QtWidgets.QLabel(self.group_Parameters)
        self.label_Tf.setMinimumSize(QtCore.QSize(51, 21))
        self.label_Tf.setMaximumSize(QtCore.QSize(51, 21))
        self.label_Tf.setText("")
#        self.label_Tf.setPixmap(QtGui.QPixmap("fig_Tf.png"))
        self.label_Tf.setScaledContents(True)
        self.label_Tf.setObjectName("label_Tf")
        self.horizontalLayout_12.addWidget(self.label_Tf)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem13)
        self.lineEdit_Tf = QtWidgets.QLineEdit(self.group_Parameters)
        self.lineEdit_Tf.setMinimumSize(QtCore.QSize(113, 20))
        self.lineEdit_Tf.setMaximumSize(QtCore.QSize(113, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_Tf.setFont(font)
        self.lineEdit_Tf.setObjectName("lineEdit_Tf")
        self.horizontalLayout_12.addWidget(self.lineEdit_Tf)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_DeltaT = QtWidgets.QLabel(self.group_Parameters)
        self.label_DeltaT.setMinimumSize(QtCore.QSize(61, 21))
        self.label_DeltaT.setMaximumSize(QtCore.QSize(61, 21))
        self.label_DeltaT.setText("")
#        self.label_DeltaT.setPixmap(QtGui.QPixmap("fig_DeltaT.png"))
        self.label_DeltaT.setScaledContents(True)
        self.label_DeltaT.setObjectName("label_DeltaT")
        self.horizontalLayout_13.addWidget(self.label_DeltaT)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem14)
        self.lineEdit_DeltaT = QtWidgets.QLineEdit(self.group_Parameters)
        self.lineEdit_DeltaT.setMinimumSize(QtCore.QSize(113, 20))
        self.lineEdit_DeltaT.setMaximumSize(QtCore.QSize(113, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_DeltaT.setFont(font)
        self.lineEdit_DeltaT.setObjectName("lineEdit_DeltaT")
        self.horizontalLayout_13.addWidget(self.lineEdit_DeltaT)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_Bi = QtWidgets.QLabel(self.group_Parameters)
        self.label_Bi.setMinimumSize(QtCore.QSize(51, 21))
        self.label_Bi.setMaximumSize(QtCore.QSize(51, 21))
        self.label_Bi.setText("")
#        self.label_Bi.setPixmap(QtGui.QPixmap("fig_Bi.png"))
        self.label_Bi.setScaledContents(True)
        self.label_Bi.setObjectName("label_Bi")
        self.horizontalLayout_14.addWidget(self.label_Bi)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem15)
        self.lineEdit_Bi = QtWidgets.QLineEdit(self.group_Parameters)
        self.lineEdit_Bi.setMinimumSize(QtCore.QSize(113, 20))
        self.lineEdit_Bi.setMaximumSize(QtCore.QSize(113, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_Bi.setFont(font)
        self.lineEdit_Bi.setObjectName("lineEdit_Bi")
        self.horizontalLayout_14.addWidget(self.lineEdit_Bi)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_Bf = QtWidgets.QLabel(self.group_Parameters)
        self.label_Bf.setMinimumSize(QtCore.QSize(51, 21))
        self.label_Bf.setMaximumSize(QtCore.QSize(51, 21))
        self.label_Bf.setText("")
#        self.label_Bf.setPixmap(QtGui.QPixmap("fig_Bf.png"))
        self.label_Bf.setScaledContents(True)
        self.label_Bf.setObjectName("label_Bf")
        self.horizontalLayout_15.addWidget(self.label_Bf)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem16)
        self.lineEdit_Bf = QtWidgets.QLineEdit(self.group_Parameters)
        self.lineEdit_Bf.setMinimumSize(QtCore.QSize(113, 20))
        self.lineEdit_Bf.setMaximumSize(QtCore.QSize(113, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_Bf.setFont(font)
        self.lineEdit_Bf.setObjectName("lineEdit_Bf")
        self.horizontalLayout_15.addWidget(self.lineEdit_Bf)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_DeltaB = QtWidgets.QLabel(self.group_Parameters)
        self.label_DeltaB.setMinimumSize(QtCore.QSize(61, 21))
        self.label_DeltaB.setMaximumSize(QtCore.QSize(61, 21))
        self.label_DeltaB.setText("")
#        self.label_DeltaB.setPixmap(QtGui.QPixmap("fig_DeltaB.png"))
        self.label_DeltaB.setScaledContents(True)
        self.label_DeltaB.setObjectName("label_DeltaB")
        self.horizontalLayout_16.addWidget(self.label_DeltaB)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem17)
        self.lineEdit_DeltaB = QtWidgets.QLineEdit(self.group_Parameters)
        self.lineEdit_DeltaB.setMinimumSize(QtCore.QSize(113, 20))
        self.lineEdit_DeltaB.setMaximumSize(QtCore.QSize(113, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_DeltaB.setFont(font)
        self.lineEdit_DeltaB.setObjectName("lineEdit_DeltaB")
        self.horizontalLayout_16.addWidget(self.lineEdit_DeltaB)
        self.verticalLayout_2.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_Deltasigma = QtWidgets.QLabel(self.group_Parameters)
        self.label_Deltasigma.setMinimumSize(QtCore.QSize(31, 16))
        self.label_Deltasigma.setMaximumSize(QtCore.QSize(31, 16))
        self.label_Deltasigma.setText("")
#        self.label_Deltasigma.setPixmap(QtGui.QPixmap("fig_Deltasigma.png"))
        self.label_Deltasigma.setScaledContents(True)
        self.label_Deltasigma.setObjectName("label_Deltasigma")
        self.horizontalLayout_17.addWidget(self.label_Deltasigma)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem18)
        self.lineEdit_Deltasigma = QtWidgets.QLineEdit(self.group_Parameters)
        self.lineEdit_Deltasigma.setMinimumSize(QtCore.QSize(113, 20))
        self.lineEdit_Deltasigma.setMaximumSize(QtCore.QSize(113, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_Deltasigma.setFont(font)
        self.lineEdit_Deltasigma.setObjectName("lineEdit_Deltasigma")
        self.horizontalLayout_17.addWidget(self.lineEdit_Deltasigma)
        self.verticalLayout_2.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_19.addWidget(self.group_Parameters)
        self.group_Plots = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.group_Plots.setFont(font)
        self.group_Plots.setObjectName("group_Plots")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.group_Plots)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_M_vs_T = QtWidgets.QCheckBox(self.group_Plots)
        self.checkBox_M_vs_T.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("gui_mce/fig_M_vs_T.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_M_vs_T.setIcon(icon)
        self.checkBox_M_vs_T.setIconSize(QtCore.QSize(50, 50))
        self.checkBox_M_vs_T.setObjectName("checkBox_M_vs_T")
        self.gridLayout.addWidget(self.checkBox_M_vs_T, 0, 0, 1, 1)
        self.checkBox_SM_vs_T = QtWidgets.QCheckBox(self.group_Plots)
        self.checkBox_SM_vs_T.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("gui_mce/fig_SM_vs_T.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_SM_vs_T.setIcon(icon1)
        self.checkBox_SM_vs_T.setIconSize(QtCore.QSize(60, 60))
        self.checkBox_SM_vs_T.setObjectName("checkBox_SM_vs_T")
        self.gridLayout.addWidget(self.checkBox_SM_vs_T, 0, 1, 1, 1)
        self.checkBox_F_vs_T = QtWidgets.QCheckBox(self.group_Plots)
        self.checkBox_F_vs_T.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("gui_mce/fig_F_vs_T.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_F_vs_T.setIcon(icon2)
        self.checkBox_F_vs_T.setIconSize(QtCore.QSize(45, 45))
        self.checkBox_F_vs_T.setObjectName("checkBox_F_vs_T")
        self.gridLayout.addWidget(self.checkBox_F_vs_T, 0, 2, 1, 1)
        self.checkBox_M_vs_B = QtWidgets.QCheckBox(self.group_Plots)
        self.checkBox_M_vs_B.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("gui_mce/fig_M_vs_B.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_M_vs_B.setIcon(icon3)
        self.checkBox_M_vs_B.setIconSize(QtCore.QSize(50, 50))
        self.checkBox_M_vs_B.setObjectName("checkBox_M_vs_B")
        self.gridLayout.addWidget(self.checkBox_M_vs_B, 1, 0, 1, 1)
        self.checkBox_SL_vs_T = QtWidgets.QCheckBox(self.group_Plots)
        self.checkBox_SL_vs_T.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("gui_mce/fig_SL_vs_T.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_SL_vs_T.setIcon(icon4)
        self.checkBox_SL_vs_T.setIconSize(QtCore.QSize(50, 50))
        self.checkBox_SL_vs_T.setObjectName("checkBox_SL_vs_T")
        self.gridLayout.addWidget(self.checkBox_SL_vs_T, 1, 1, 1, 1)
        self.checkBox_F_vs_B = QtWidgets.QCheckBox(self.group_Plots)
        self.checkBox_F_vs_B.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("gui_mce/fig_F_vs_B.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_F_vs_B.setIcon(icon5)
        self.checkBox_F_vs_B.setIconSize(QtCore.QSize(45, 45))
        self.checkBox_F_vs_B.setObjectName("checkBox_F_vs_B")
        self.gridLayout.addWidget(self.checkBox_F_vs_B, 1, 2, 1, 1)
        self.checkBox_M_vs_TB = QtWidgets.QCheckBox(self.group_Plots)
        self.checkBox_M_vs_TB.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("gui_mce/fig_M_vs_TB.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_M_vs_TB.setIcon(icon6)
        self.checkBox_M_vs_TB.setIconSize(QtCore.QSize(70, 70))
        self.checkBox_M_vs_TB.setObjectName("checkBox_M_vs_TB")
        self.gridLayout.addWidget(self.checkBox_M_vs_TB, 2, 0, 1, 1)
        self.checkBox_Stot_vs_T = QtWidgets.QCheckBox(self.group_Plots)
        self.checkBox_Stot_vs_T.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("gui_mce/fig_Stot_vs_T.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_Stot_vs_T.setIcon(icon7)
        self.checkBox_Stot_vs_T.setIconSize(QtCore.QSize(60, 60))
        self.checkBox_Stot_vs_T.setObjectName("checkBox_Stot_vs_T")
        self.gridLayout.addWidget(self.checkBox_Stot_vs_T, 2, 1, 1, 1)
        self.checkBox_Ts_vs_B = QtWidgets.QCheckBox(self.group_Plots)
        self.checkBox_Ts_vs_B.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("gui_mce/fig_Ts_vs_B.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_Ts_vs_B.setIcon(icon8)
        self.checkBox_Ts_vs_B.setIconSize(QtCore.QSize(55, 55))
        self.checkBox_Ts_vs_B.setObjectName("checkBox_Ts_vs_B")
        self.gridLayout.addWidget(self.checkBox_Ts_vs_B, 2, 2, 1, 1)
        self.checkBox_U_vs_T = QtWidgets.QCheckBox(self.group_Plots)
        self.checkBox_U_vs_T.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("gui_mce/fig_U_vs_T.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_U_vs_T.setIcon(icon9)
        self.checkBox_U_vs_T.setIconSize(QtCore.QSize(40, 40))
        self.checkBox_U_vs_T.setObjectName("checkBox_U_vs_T")
        self.gridLayout.addWidget(self.checkBox_U_vs_T, 3, 0, 1, 1)
        self.checkBox_DeltaS_vs_T = QtWidgets.QCheckBox(self.group_Plots)
        self.checkBox_DeltaS_vs_T.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("gui_mce/fig_DeltaS_vs_T.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_DeltaS_vs_T.setIcon(icon10)
        self.checkBox_DeltaS_vs_T.setIconSize(QtCore.QSize(50, 50))
        self.checkBox_DeltaS_vs_T.setObjectName("checkBox_DeltaS_vs_T")
        self.gridLayout.addWidget(self.checkBox_DeltaS_vs_T, 3, 1, 1, 1)
        self.checkBox_FM_vs_T = QtWidgets.QCheckBox(self.group_Plots)
        self.checkBox_FM_vs_T.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("gui_mce/fig_FM_vs_T.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_FM_vs_T.setIcon(icon11)
        self.checkBox_FM_vs_T.setIconSize(QtCore.QSize(60, 60))
        self.checkBox_FM_vs_T.setObjectName("checkBox_FM_vs_T")
        self.gridLayout.addWidget(self.checkBox_FM_vs_T, 3, 2, 1, 1)
        self.checkBox_Mhys_vs_TB = QtWidgets.QCheckBox(self.group_Plots)
        self.checkBox_Mhys_vs_TB.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("gui_mce/fig_Mhys_vs_T.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_Mhys_vs_TB.setIcon(icon12)
        self.checkBox_Mhys_vs_TB.setIconSize(QtCore.QSize(70, 70))
        self.checkBox_Mhys_vs_TB.setObjectName("checkBox_Mhys_vs_TB")
        self.gridLayout.addWidget(self.checkBox_Mhys_vs_TB, 4, 0, 1, 1)
        self.checkBox_maxDeltaS_vs_B = QtWidgets.QCheckBox(self.group_Plots)
        self.checkBox_maxDeltaS_vs_B.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("gui_mce/fig_maxDeltaS_vs_T.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_maxDeltaS_vs_B.setIcon(icon13)
        self.checkBox_maxDeltaS_vs_B.setIconSize(QtCore.QSize(110, 110))
        self.checkBox_maxDeltaS_vs_B.setObjectName("checkBox_maxDeltaS_vs_B")
        self.gridLayout.addWidget(self.checkBox_maxDeltaS_vs_B, 4, 1, 1, 1)
        self.checkBox_FM_vs_M = QtWidgets.QCheckBox(self.group_Plots)
        self.checkBox_FM_vs_M.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("gui_mce/fig_FM_vs_sigma.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_FM_vs_M.setIcon(icon14)
        self.checkBox_FM_vs_M.setIconSize(QtCore.QSize(60, 60))
        self.checkBox_FM_vs_M.setObjectName("checkBox_FM_vs_M")
        self.gridLayout.addWidget(self.checkBox_FM_vs_M, 4, 2, 1, 1)
        self.checkBox_SM_vs_M = QtWidgets.QCheckBox(self.group_Plots)
        self.checkBox_SM_vs_M.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("gui_mce/fig_SM_vs_sigma.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_SM_vs_M.setIcon(icon15)
        self.checkBox_SM_vs_M.setIconSize(QtCore.QSize(50, 50))
        self.checkBox_SM_vs_M.setObjectName("checkBox_SM_vs_M")
        self.gridLayout.addWidget(self.checkBox_SM_vs_M, 5, 1, 1, 1)
        self.checkBox_FL_vs_T = QtWidgets.QCheckBox(self.group_Plots)
        self.checkBox_FL_vs_T.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("gui_mce/fig_FL_vs_T.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_FL_vs_T.setIcon(icon16)
        self.checkBox_FL_vs_T.setIconSize(QtCore.QSize(50, 50))
        self.checkBox_FL_vs_T.setObjectName("checkBox_FL_vs_T")
        self.gridLayout.addWidget(self.checkBox_FL_vs_T, 5, 2, 1, 1)
        self.checkBox_Ftot_vs_M = QtWidgets.QCheckBox(self.group_Plots)
        self.checkBox_Ftot_vs_M.setText("")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("gui_mce/fig_Ftot_vs_sigma.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_Ftot_vs_M.setIcon(icon17)
        self.checkBox_Ftot_vs_M.setIconSize(QtCore.QSize(60, 60))
        self.checkBox_Ftot_vs_M.setObjectName("checkBox_Ftot_vs_M")
        self.gridLayout.addWidget(self.checkBox_Ftot_vs_M, 6, 2, 1, 1)
        self.checkBox_Ftotheatcool_vs_TB = QtWidgets.QCheckBox(self.group_Plots)
        self.checkBox_Ftotheatcool_vs_TB.setText("")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("gui_mce/fig_Ftotheatcool_vs_TB.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox_Ftotheatcool_vs_TB.setIcon(icon18)
        self.checkBox_Ftotheatcool_vs_TB.setIconSize(QtCore.QSize(120, 120))
        self.checkBox_Ftotheatcool_vs_TB.setObjectName("checkBox_Ftotheatcool_vs_TB")
        self.gridLayout.addWidget(self.checkBox_Ftotheatcool_vs_TB, 7, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem19)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.checkBox_Savetxt = QtWidgets.QCheckBox(self.group_Plots)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_Savetxt.setFont(font)
        self.checkBox_Savetxt.setIconSize(QtCore.QSize(16, 16))
        self.checkBox_Savetxt.setObjectName("checkBox_Savetxt")
        self.horizontalLayout_18.addWidget(self.checkBox_Savetxt)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem20)
        self.pushButton_Run = QtWidgets.QPushButton(self.group_Plots)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_Run.setFont(font)
        self.pushButton_Run.setObjectName("pushButton_Run")
        self.horizontalLayout_18.addWidget(self.pushButton_Run)
        self.verticalLayout.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19.addWidget(self.group_Plots)
        self.verticalLayout_3.addLayout(self.horizontalLayout_19)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 748, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSuggestion = QtWidgets.QAction(MainWindow)
        self.actionSuggestion.setObjectName("actionSuggestion")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
#        self.actionDebug = QtWidgets.QAction(MainWindow)
#        self.actionDebug.setObjectName("actionDebug")
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionSuggestion)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
#        self.menuHelp.addAction(self.actionDebug)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

#        self.label_J.setPixmap(QtGui.QPixmap(os.path.join(path, "fig_J.png")))
        self.label_J.setPixmap(QtGui.QPixmap("gui_mce/fig_J.png"))
        self.label_gJ.setPixmap(QtGui.QPixmap("gui_mce/fig_gJ.png"))
        self.label_TC1.setPixmap(QtGui.QPixmap("gui_mce/fig_TC1.png"))
        self.label_TC2.setPixmap(QtGui.QPixmap("gui_mce/fig_TC2.png"))
        self.label_ThetaD1.setPixmap(QtGui.QPixmap("gui_mce/fig_ThetaD1.png"))
        self.label_ThetaD2.setPixmap(QtGui.QPixmap("gui_mce/fig_ThetaD2.png"))
        self.label_DeltaF.setPixmap(QtGui.QPixmap("gui_mce/fig_DeltaF.png"))
        self.label_N.setPixmap(QtGui.QPixmap("gui_mce/fig_N.png"))
        self.label_Nm.setPixmap(QtGui.QPixmap("gui_mce/fig_Nm.png"))

        self.label_Ti.setPixmap(QtGui.QPixmap("gui_mce/fig_Ti.png"))
        self.label_Tf.setPixmap(QtGui.QPixmap("gui_mce/fig_Tf.png"))
        self.label_DeltaT.setPixmap(QtGui.QPixmap("gui_mce/fig_DeltaT.png"))
        self.label_Bi.setPixmap(QtGui.QPixmap("gui_mce/fig_Bi.png"))
        self.label_Bf.setPixmap(QtGui.QPixmap("gui_mce/fig_Bf.png"))
        self.label_DeltaB.setPixmap(QtGui.QPixmap("gui_mce/fig_DeltaB.png"))
        self.label_Deltasigma.setPixmap(QtGui.QPixmap("gui_mce/fig_Deltasigma.png"))


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Magnetocaloric Effect"))
        self.label_Name.setToolTip(_translate("MainWindow", "<html><head/><body><p>Name of compound</p></body></html>"))
        self.label_Name.setText(_translate("MainWindow", "Name"))
        self.label_Database.setText(_translate("MainWindow", "Database"))
        self.pushButton_Save.setText(_translate("MainWindow", "Save/Update"))
        self.pushButton_Delete.setText(_translate("MainWindow", "Delete"))
        self.group_Parameters.setTitle(_translate("MainWindow", "Parameters"))
        self.label_J.setToolTip(_translate("MainWindow", "Total Angular Momentum"))
        self.label_gJ.setToolTip(_translate("MainWindow", "Landé g-factor"))
        self.label_TC1.setToolTip(_translate("MainWindow", "Curie Temperature of Structure 1"))
        self.label_TC2.setToolTip(_translate("MainWindow", "Curie Temperature of Structure 2"))
        self.label_ThetaD1.setToolTip(_translate("MainWindow", "Debye Temperature of Structure 1"))
        self.label_ThetaD2.setToolTip(_translate("MainWindow", "Debye Temperature of Structure 2"))
        self.label_DeltaF.setToolTip(_translate("MainWindow", "Free Energy Difference at 0 K"))
        self.label_N.setToolTip(_translate("MainWindow", "Number of Atoms in a Unit Cell"))
        self.label_Nm.setToolTip(_translate("MainWindow", "Number of Magnetic Moment in a Unit Cell"))
        self.label_Ti.setToolTip(_translate("MainWindow", "Initial Temperature"))
        self.label_Tf.setToolTip(_translate("MainWindow", "Final Temperature"))
        self.label_DeltaT.setToolTip(_translate("MainWindow", "Temperature Step"))
        self.label_Bi.setToolTip(_translate("MainWindow", "Initial Magnetic Field"))
        self.label_Bf.setToolTip(_translate("MainWindow", "Final Magnetic Field"))
        self.label_DeltaB.setToolTip(_translate("MainWindow", "Mangetic Field Step"))
        self.label_Deltasigma.setToolTip(_translate("MainWindow", "Reduced Magnetization Step"))
        self.group_Plots.setTitle(_translate("MainWindow", "Plots"))
        self.checkBox_M_vs_T.setToolTip(_translate("MainWindow", "Magnetization as a function of Temperature"))
        self.checkBox_SM_vs_T.setToolTip(_translate("MainWindow", "Magnetic Entropy as a Function of Temperature"))
        self.checkBox_F_vs_T.setToolTip(_translate("MainWindow", "Free Energy as a function of Temperature"))
        self.checkBox_M_vs_B.setToolTip(_translate("MainWindow", "Magnetization as a function of Magnetic Field"))
        self.checkBox_SL_vs_T.setToolTip(_translate("MainWindow", "Lattice Entropy as a function of Temperature"))
        self.checkBox_F_vs_B.setToolTip(_translate("MainWindow", "Free Energy as a function of Magnetic Field"))
        self.checkBox_M_vs_TB.setToolTip(_translate("MainWindow", "Magnetization as a function of Temperature and Magnetic Field"))
        self.checkBox_Stot_vs_T.setToolTip(_translate("MainWindow", "Total Entropy as a function of Temperature"))
        self.checkBox_Ts_vs_B.setToolTip(_translate("MainWindow", "Transition Temperature as a function of Magnetic Field"))
        self.checkBox_U_vs_T.setToolTip(_translate("MainWindow", "Internal Energy as a function of Temperature"))
        self.checkBox_DeltaS_vs_T.setToolTip(_translate("MainWindow", "Entropy change as a function of Temperature"))
        self.checkBox_FM_vs_T.setToolTip(_translate("MainWindow", "Magnetic Free Energy as a function of Temperature"))
        self.checkBox_Mhys_vs_TB.setToolTip(_translate("MainWindow", "Magnetic hysteresis as a function of Temperature and Magnetic Field"))
        self.checkBox_maxDeltaS_vs_B.setToolTip(_translate("MainWindow", "Maximum Entropy Variation as a function of Magnetic Field"))
        self.checkBox_FM_vs_M.setToolTip(_translate("MainWindow", "Magnetic Free Energy as a function of Reduced Magnetization"))
        self.checkBox_SM_vs_M.setToolTip(_translate("MainWindow", "Magnetic Entropy as a function of Reduced Magnetization"))
        self.checkBox_FL_vs_T.setToolTip(_translate("MainWindow", "Lattice Free Energy as a function of Temperature"))
        self.checkBox_Ftot_vs_M.setToolTip(_translate("MainWindow", "Free Energy as a function of Reduced Magnetization"))
        self.checkBox_Ftotheatcool_vs_TB.setToolTip(_translate("MainWindow", "Free Energy on Heating and Cooling as a function of Temperature and Magnetic Field"))
        self.checkBox_Savetxt.setToolTip(_translate("MainWindow", "Save to a .txt file"))
        self.checkBox_Savetxt.setText(_translate("MainWindow", "Save to .txt"))
        self.pushButton_Run.setToolTip(_translate("MainWindow", "Run Plots"))
        self.pushButton_Run.setText(_translate("MainWindow", "Run"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionSuggestion.setText(_translate("MainWindow", "Suggestion"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
#        self.action.setText(_translate("MainWindow", "Debug"))
#        self.actionDebug.setText(_translate("MainWindow", "Debug"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

